
/* 
    Automatically generated by Jack The Repeater from lang/lang_specs.ctmpl
    Do not modify this file
*/


#ifndef __LANG_SPECS_H__
#define __LANG_SPECS_H__

#include <ttypes.h>
#include <ixemes.h>

const char   *lang_strs[] = {"DE","EN","ES","FI","FR","PT","SE", ""};
const ixid_t lang_codes[] = {LANG_DE,LANG_EN,LANG_ES,LANG_FI,LANG_FR,LANG_PT,LANG_SE, 0};

#endif /* __LANG_SPECS_H__ */

