
/* 
    Automatically generated by Jack The Repeater from lang/lang_conf.ctmpl
    Do not modify this file
*/

#include <ixemes.h>

#ifndef XID_LANG_DE
#error Language LANG_DE not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_DE.lm			XID_LANG_DE
#endif

#ifndef XID_LANG_EN
#error Language LANG_EN not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_EN.lm			XID_LANG_EN
#endif

#ifndef XID_LANG_ES
#error Language LANG_ES not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_ES.lm			XID_LANG_ES
#endif

#ifndef XID_LANG_FI
#error Language LANG_FI not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_FI.lm			XID_LANG_FI
#endif

#ifndef XID_LANG_FR
#error Language LANG_FR not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_FR.lm			XID_LANG_FR
#endif

#ifndef XID_LANG_PT
#error Language LANG_PT not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_PT.lm			XID_LANG_PT
#endif

#ifndef XID_LANG_SE
#error Language LANG_SE not specified in ixemes.h. Bad things will happen.
#else
lm/lm_LANG_SE.lm			XID_LANG_SE
#endif

