
/* 
    Automatically generated by Jack The Repeater from lang/snowball_lemmatize.ctmpl
    Do not modify this file
*/

/*
 *   lang/snowball_lemmatize.c
 *   Lemmatizing with Snowball
 *   
 *   Copyright (C) 2004-2005 Ville H. Tuulos
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#include <string.h>

#include <api.h>

#include <dub.h>
#include <ttypes.h>
#include <ixemes.h>


#ifndef XID_LANG_EN
#error Language LANG_EN not specified in ixemes.h. Bad things will happen.
#else
static struct SN_env *zLANG_EN;
extern struct SN_env *LANG_EN_create_env(void);
void LANG_EN_stem(struct SN_env *s);
#endif

#ifndef XID_LANG_SE
#error Language LANG_SE not specified in ixemes.h. Bad things will happen.
#else
static struct SN_env *zLANG_SE;
extern struct SN_env *LANG_SE_create_env(void);
void LANG_SE_stem(struct SN_env *s);
#endif

#ifndef XID_LANG_FI
#error Language LANG_FI not specified in ixemes.h. Bad things will happen.
#else
static struct SN_env *zLANG_FI;
extern struct SN_env *LANG_FI_create_env(void);
void LANG_FI_stem(struct SN_env *s);
#endif


void snowball_init(){

        
        zLANG_EN = LANG_EN_create_env();
        
        zLANG_SE = LANG_SE_create_env();
        
        zLANG_FI = LANG_FI_create_env();
        
}

const char *snowball_lemmatize(const char *token, u32 lang)
{
        switch (lang){

                
                case XID_LANG_EN: 
                        SN_set_current(zLANG_EN, strlen(token), token);
                        LANG_EN_stem(zLANG_EN);
                        zLANG_EN->p[zLANG_EN->l] = 0;
                        return zLANG_EN->p;
                
                case XID_LANG_SE: 
                        SN_set_current(zLANG_SE, strlen(token), token);
                        LANG_SE_stem(zLANG_SE);
                        zLANG_SE->p[zLANG_SE->l] = 0;
                        return zLANG_SE->p;
                
                case XID_LANG_FI: 
                        SN_set_current(zLANG_FI, strlen(token), token);
                        LANG_FI_stem(zLANG_FI);
                        zLANG_FI->p[zLANG_FI->l] = 0;
                        return zLANG_FI->p;
                

                default:
                        return NULL;
        }

        return NULL;
}

